### ISSUE TITLE
Add Timed Tiles

### ISSUE THREAD

**Issue by Panzarotti** [Panzarotti/EleeStuff#19]
The screen won't move at all unless you tap a tile. When you do tap a tile, the screen shifts one tile. Make there be a time limit, so it doesn't go forever. If you tap in a row that is not the bottom, shift all rows at and above the row you tapped. Leave lower rows stationary.

**Comment by kuhrusty** [comment]
Things still to do here:
- Add a time limit, or a gradually increasing minimum-average-tiles-per-minute rate--something to keep the game from running forever.
- Display time remaining or whatever on the screen while playing.
- We talked about keeping the list of rows in a LinkedList; it's currently using ArrayList, which may not be as efficient (although there don't seem to be performance problems).

**Comment by kuhrusty** [comment]
> We talked about keeping the list of rows in a LinkedList

The method I was forgetting for traversing the list in reverse is `descendingIterator()`.

**Comment by kuhrusty** [comment]
> - Add a time limit, or a gradually increasing minimum-average-tiles-per-minute rate--something to keep the game from running forever.
> - Display time remaining or whatever on the screen while playing.

These are done, although the high-score-recording stuff needs to include the time limit so that, when we're figuring out whether you got a high score, you're only being compared to other plays using the same time limit.
